### ISSUE TITLE
[price] price can be denominated in multiple currencies

### ISSUE THREAD

**Issue by bitbeckers** [hypercerts-org/hypercerts-app#157]
Currently, the marketplace listing prices are hardcoded with 'ETH' as symbol and `lowestPrice` reflects that same denomination. The marketplace supports multiple currencies and we should handle them all properly.

Multiple updates in the marketplace are required,

- [x] hypercerts-org/hypercerts-app#158
- [x] hypercerts-org/marketplace-sdk#26
- [x] hypercerts-org/hypercerts-app#160
- [x] hypercerts-org/hypercerts-app#161
